"""fix model error

Revision ID: 79bda4011de2
Revises: f1ac5bb66d16
Create Date: 2025-02-14 07:39:40.521229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bda4011de2'
down_revision: Union[str, None] = 'f1ac5bb66d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Integer(), server_default=sa.text('3'), nullable=True))
    op.create_foreign_key(None, 'users', 'status', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
